### ISSUE TITLE
Rule for `org.apache.tomcat.embed:tomcat-embed-websocket`

### ISSUE THREAD

**Issue by boris-petrov** [gradlex-org/java-ecosystem-capabilities#24]
It conflicts with `org.eclipse.jetty.toolchain:jetty-jakarta-websocket-api:2.0.0`.

**Comment by jjohannes** [comment]
There are more things here to consider.

Other `org.apache.tomcat.embed` have similar conflicts. E.g. `tomcat-embed-core` conflicts with `javax.annotation-api`.

We don't need to solve all of these at once, but should add at least a minimal set that takes the javax/jakarta spec this is all based into account.
