### ISSUE TITLE
Bump version to 1.0

### ISSUE THREAD

**Issue by vlsi** [gradlex-org/java-ecosystem-capabilities#3]
Is the plugin usable?
If so, it deserves 1.0 :)

See https://github.com/gradle-nexus/publish-plugin/issues/47#issuecomment-775834008

**Comment by jjohannes** [comment]
Thanks for the suggestion. I wanted to throw this out and gather some feedback first. I'll consider doing this soonish.

**Comment by jjohannes** [comment]
Checklist for 1.0:

- [ ] Make sure documentation is complete, including docs for `javaEcosystemCapabilities` extension
- [ ] Adjust project structure to use https://github.com/gradlex-org/plugin-publish-conventions
- [ ] Make sure README and LICENSE information is in sync with other GradleX projects
- [ ] Move project to https://github.com/gradlex-org and publish using new Plugin ID
