### ISSUE TITLE
Add `org.glassfish.hk2.external:jakarta.inject` to `JavaxInjectApiRule`

### ISSUE THREAD

**Issue by boris-petrov** [gradlex-org/java-ecosystem-capabilities#41]
It conflicts with `org.glassfish.hk2.external:jakarta.inject`

**Comment by jjohannes** [comment]
Should probably be added to: https://github.com/gradlex-org/java-ecosystem-capabilities/blob/main/src/main/java/org/gradlex/javaecosystem/capabilities/rules/JavaxInjectApiRule.java

**Comment by boris-petrov** [comment]
@jjohannes I believe you missed adding `org.glassfish.hk2.external:jakarta.inject`.

**Comment by jjohannes** [comment]
Mh. Guess I should come up with some issue template for better overview. Sometimes hard to keep track when everything is named different but kind of the same.

Thanks for double checking.
