### ISSUE TITLE
AopAlliance rule > gives troubles for Spring 4.2 and earlier

### ISSUE THREAD

**Issue by kmoens** [gradlex-org/java-ecosystem-capabilities#58]
We still have some legacy projects which use an unsupported Spring version. This gives an issue with the AopAlliance rule.

spring-aop 4.2 and earlier have a direct dependency on the aopalliance. Due to the capability plugin, we only get the spring-aop, which gives runtime errors with these Spring versions.

Starting from Spring 4.3 they have removed the dependency on aopalliance.

For now, we've disabled the rule with us, but maybe it is a good idea to integrate this version constraint as part of the rule?

**Comment by jjohannes** [comment]
Fixed by #60
