### ISSUE TITLE
Rule for `com.google.code.findbugs:findbugs-annotations`.

### ISSUE THREAD

**Issue by boris-petrov** [gradlex-org/java-ecosystem-capabilities#62]
It conflicts with `com.github.spotbugs:spotbugs-annotations` which is the newer artifact.

**Comment by boris-petrov** [comment]
@jjohannes thanks for the new release!

However, there is something strange going on on my side with the new version:

```
Could not determine the dependencies of task ':backend:pmdIntegrationTest'.
> Could not resolve all task dependencies for configuration ':backend:integrationTestPmdAuxClasspath'.
   > Could not resolve ch.qos.logback:logback-core:1.3.14.
     Required by:
         project :backend > ch.qos.logback:logback-classic:1.3.14
      > Could not resolve ch.qos.logback:logback-core:1.3.14: Resolution strategy disallows usage of dynamic versions
   > Could not resolve ch.qos.logback:logback-core:{strictly [1.2.9, 2[}.
     Required by:
         project :backend > com.github.spotbugs:spotbugs-annotations:4.8.3
      > Could not resolve ch.qos.logback:logback-core:{strictly [1.2.9, 2[}: Resolution strategy disallows usage of dynamic versions
```

This doesn't happen with 1.4.

I'm not sure exactly what is happening but I do have:

```gradle
compileOnly(libs.spotbugs.annotations) {
	exclude group: 'ch.qos.logback', module: 'logback-core' // causes problems because `SpotBugs` uses dynamic versioning which we've disabled
}
```

And

```gradle
configurations.configureEach {
	resolutionStrategy {
		failOnNonReproducibleResolution()
	}
}
```

In my `build.gradle` files.

Do you understand why this happens? Is it a problem with my configuration or is that something Gradle does strangely?

**Comment by boris-petrov** [comment]
@jjohannes thank you for your time and help!

I created [this](https://github.com/boris-petrov/gradle-spotbugs-bug) reproduction. Running `./gradlew check` on this leads to a similar error. It's not exactly the same as my case but I think it's OK? Are you suggesting I open an issue in Gradle or in SpotBugs?

**Comment by jjohannes** [comment]
Thank you for the reproducer @boris-petrov. I think this is a bug in Gradle. I took the liberty to open an issue: https://github.com/gradle/gradle/issues/27883

Feel free to comment there if you have anything to add.
