### ISSUE TITLE
ComponentStatusRule conflicts

### ISSUE THREAD

**Issue by ko-at-work** [gradlex-org/java-ecosystem-capabilities#65]
We have our own ComponentMetadataRule that sets the status to "milestone" when matching particular patterns, such as "RC".

This is conflict with the new ComponentStatusRule that was added to this project that sets the status to "integration".

While I appreciate the recognition that latest.release is largely unusable due to artifacts published without this information, the global application of ComponentStatusRule seems problematic since it is encroaching into the territory of opinion/preference. With capabilities, this is more clear cut and less problematic, so the inability to disable those rules seems reasonable.

However, since this is being applied to any and all artifacts, I would ask for an option to disable this rule.

**Comment by jjohannes** [comment]
Thank you for this feedback @ko-at-work. I was mostly thinking about components **not** being release without thinking too much about other statuses they may get. From the perspective you shared, I agree that it is likely too opinionated to be applied everywhere. I might remove the automatic applying altogether but keep the rule implementation itself so users can use it as a convenience if they want.

One thing I wonder though: Can't you add your rule "on top" of the plugin? Then your rule should override what this rule is doing.

**Comment by jjohannes** [comment]
Thank you for elaboration @ko-at-work. Much appreciated. In hindsight, I should have not added an `all` rule, no matter what it is about. I turned the rule into a _custom rule_  and made the "markers" configurable. That's something I would like to use in some projects, but this way it is completely optional.
