### ISSUE TITLE
Change how alignment rules works

### ISSUE THREAD

**Issue by britter** [gradlex-org/java-ecosystem-capabilities#71]
- do not use ‘all’
- `belongsTo` or constraints

**Comment by ljacomet** [comment]
Also included alignment for Slf4J 2.0.8+ based on the published BOM

**Comment by jjohannes** [comment]
With #81, the alignment rules are now also defined through an Enum, using similar structure as the capability rules.

We can use this to add more alignment in the future and address #22.
