### ISSUE TITLE
Better name for 'org.gradlex.java-ecosystem-capabilities-base'

### ISSUE THREAD

**Issue by britter** [gradlex-org/java-ecosystem-capabilities#72]
Also register an ID for that plugin

**Comment by jjohannes** [comment]
...and reconsider if we want/need to different plugins and extensions for the resolution part as the logging plugin does nothing now unless you explicitly configure it anyway.

**Comment by britter** [comment]
During the team meeting on Mar 15th, we discussed calling the base plugin `org.gradlex.jvm-ecosystem-conflict-detection` and the DSL plugin `org.gradlex.jvm-eosystem-conflict-resolution`
