### ISSUE TITLE
Port logging capabilities documentation

### ISSUE THREAD

**Issue by ljacomet** [gradlex-org/java-ecosystem-capabilities#83]
* Needs to be moved from the [original plugin](https://github.com/ljacomet/logging-capabilities) README
* Might consider moving the docs to asciidoc as is done for [gradlex-org/build-parameters](https://github.com/gradlex-org/build-parameters)

**Comment by jjohannes** [comment]
Closing this as the porting has been done in #92, which will be merged when we release(d)
